// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(PolicyDetailsDBContext))]
    [Migration("20240829105554_2nd migration")]
    partial class _2ndmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Domain.PolicyDetailsModel", b =>
                {
                    b.Property<Guid>("QuotationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarYearOfMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuotationStatus")
                        .HasColumnType("int");

                    b.HasKey("QuotationNumber");

                    b.ToTable("policyDetails");

                    b.HasData(
                        new
                        {
                            QuotationNumber = new Guid("418c4d9f-382b-4c15-a90c-c386f6336396"),
                            CarMake = "Mercedes",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(401),
                            PolicyOwner = "Charbel",
                            QuotationStatus = 1
                        },
                        new
                        {
                            QuotationNumber = new Guid("4c1ef98b-148e-4358-8468-545dd8199bf8"),
                            CarMake = "Camaro",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(442),
                            PolicyOwner = "Elie",
                            QuotationStatus = 1
                        },
                        new
                        {
                            QuotationNumber = new Guid("744c30e4-45fd-482c-90d6-136dfecdc9d1"),
                            CarMake = "Golf",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(445),
                            PolicyOwner = "Etienne",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("a3df4993-cb53-4752-b2e2-26c6106a40f9"),
                            CarMake = "bmw",
                            CarYearOfMake = "2020",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(455),
                            PolicyOwner = "Bob",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("6e3d51a4-22b6-4eda-823d-ed49096b624f"),
                            CarMake = "Kia",
                            CarYearOfMake = "2015",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(458),
                            PolicyOwner = "Abdo",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("cfb56a74-e103-40c2-bd08-efd76f7df9a7"),
                            CarMake = "suzuki",
                            CarYearOfMake = "2028",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(461),
                            PolicyOwner = "Roula",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("a01dee98-5c78-4c48-8552-477d29d35d87"),
                            CarMake = "Mercedes",
                            CarYearOfMake = "2012",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(463),
                            PolicyOwner = "Thierry",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("0f9f9e05-e79c-40bd-b8ed-b2568b59e6fa"),
                            CarMake = "Range",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(465),
                            PolicyOwner = "Rita",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("cac22ba8-136a-4fd3-854e-cacd002a5da6"),
                            CarMake = "jeep",
                            CarYearOfMake = "2017",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(488),
                            PolicyOwner = "James",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("69978987-f4dc-4031-8638-1ada98e0f2dd"),
                            CarMake = "BMW",
                            CarYearOfMake = "2019",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(491),
                            PolicyOwner = "Roudy",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("b4737127-01a3-45fa-83f4-82fa309bff1a"),
                            CarMake = "Lexus",
                            CarYearOfMake = "2016",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(493),
                            PolicyOwner = "Fredy",
                            QuotationStatus = 0
                        },
                        new
                        {
                            QuotationNumber = new Guid("6173ff4a-531f-4ac9-a041-cf24d0040454"),
                            CarMake = "Nissan",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 13, 55, 54, 623, DateTimeKind.Local).AddTicks(497),
                            PolicyOwner = "Miguel",
                            QuotationStatus = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
