// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(PolicyDetailsDBContext))]
    [Migration("20240829070814_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.PolicyDetails", b =>
                {
                    b.Property<Guid>("QuotationNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarYearOfMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyOwner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuotationStatus")
                        .HasColumnType("int");

                    b.HasKey("QuotationNumber");

                    b.ToTable("policyDetails");

                    b.HasData(
                        new
                        {
                            QuotationNumber = new Guid("4416443a-5779-4c8d-a756-cc63c19cd0cc"),
                            CarMake = "Mercedes",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 10, 8, 14, 518, DateTimeKind.Local).AddTicks(4971),
                            PolicyOwner = "Charbel",
                            QuotationStatus = 1
                        },
                        new
                        {
                            QuotationNumber = new Guid("fdb16cb1-06d0-4b94-8529-4382deadc5f4"),
                            CarMake = "Camaro",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 10, 8, 14, 518, DateTimeKind.Local).AddTicks(5022),
                            PolicyOwner = "Elie",
                            QuotationStatus = 1
                        },
                        new
                        {
                            QuotationNumber = new Guid("7629592b-a02d-40a0-b889-2ab39f75bc34"),
                            CarMake = "Golf",
                            CarYearOfMake = "2023",
                            CreationDate = new DateTime(2024, 8, 29, 10, 8, 14, 518, DateTimeKind.Local).AddTicks(5025),
                            PolicyOwner = "Etienne",
                            QuotationStatus = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
